export const CALCULATOR_SCREEN = 'CALCULATOR_SCREEN';
export const HISTORY_SCREEN = 'HISTORY_SCREEN';
export const SELECT_ACCOUNT_SCREEN = 'SELECT_ACCOUNT_SCREEN';
export const QRCODE_SCREEN = 'QRCODE_SCREEN';
export const CHANGE_THEME_SCREEN = 'CHANGE_THEME_SCREEN';

export const THEME_ID = 'CALCULATOR_THEME';

export const AUTH_TOKEN = 'CALCULATOR_AUTH';

export const ACCOUNT_SELECTED = 'CALCULATOR_ACCOUNT_SELECTED';

export const API_ENDPOINT = process.env.REACT_APP_API_ENDPOINT;
